.TH "CAPNG_GET_ROOTID" "3" "Sept 2020" "Red Hat" "Libcap-ng API"
.SH NAME
capng_get_rootid \- get namespace root id
.SH "SYNOPSIS"
.B #include <cap-ng.h>
.sp
uid_t capng_get_rootid(void);

.SH "DESCRIPTION"

capng_get_rootid gets the rootid for file capabilities operations. The value
is a host-endian user ID in the caller's user namespace.

.SH "RETURN VALUE"

If V3 file capabilities have not been selected, or the kernel does not
support them, it returns CAPNG_UNSET_ROOTID. Otherwise it returns the
namespace root user ID.

.SH "SEE ALSO"

.BR capng_get_caps_fd (3),
.BR capabilities (7)

.SH AUTHOR
Steve Grubb
